baseURL = 'https://example.org/'
languageCode = 'en'
title = 'Vinicius Helegda - Software Developer'
# theme = 'PaperMod'

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
  mainSections = ["projects"]
  disableSpecial1stPost = true
  defaultTheme = "dark"

[[menu.main]]
  identifier = "experiences"
  name = "Professional Experiences"
  url = "/experiences/"
  weight = 20

[[menu.main]]
  identifier = "about"
  name = "About Me"
  url = "/about/"
  weight = 30