baseURL = 'https://example.org/'
languageCode = 'en'
title = 'Vinicius Helegda - Software Developer'
# theme = 'PaperMod'

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
  mainSections = ["projects"]
  disableSpecial1stPost = true
  defaultTheme = "dark"
  disableThemeToggle = true # Desativa o botão na interface (comentado funcionalmente)

  # Define o que aparece no cabeçalho (evita que o título longo quebre o layout)
  [params.label]
    text = "Vinicius Helegda"
    displayLink = true

[[menu.main]]
  identifier = "experiences"
  name = "Experiences"
  url = "/experiences/"
  weight = 20

[[menu.main]]
  identifier = "about-me"
  name = "About Me"
  url = "/about-me/"
  weight = 30